<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2015/1/15
 * Time: 11:24
 */

namespace decorator;


class Suger extends CondimentDecorator{



    public function cost()
    {
        return parent::cost() * 0.5; // TODO: Change the autogenerated stub
    }

} 